### ISSUE TITLE
Minor: Write new function

### ISSUE THREAD

**Issue by Mowinski** [Agata-Les/rgb-hsv-fantastic-converter#2]
https://github.com/Agata-Les/rgb-hsv-fantastic-converter/blob/24aa4c0e632abb82c2b54032dd23bb6a4c0d41dd/src/rgb_hsv_converter.cpp#L8

Did you consider to write own function to find the minimum value in a tuple of three elements?
This function could use `std::min`

**Comment by Agata-Les** [comment]
I don't quite see any benefits of making an additional container out of the only three fields already included in the RGB struct, but instead I would make a method of this struct that calculates min and max of those values and stores it in a separate field. It cost additional memory but, as min and max values are often used, it will also simplify the code and prevent calculating those values multiple times or passing to multiple functions. What do you think?

**Comment by Mowinski** [comment]
Yes! This approach is more readable than my 👍 But you have to remember, that if someone/something changes one of your fields, you have to recalculate the min and max values.
